In [87]:
import pandas as pd
import numpy as np

offenses = pd.read_csv('offenses_city.csv')
race = pd.read_csv('city_census_race.csv')
police = pd.read_csv('police_city.csv')
income = pd.read_csv('city_median_income.csv')

In [88]:
offenses

,Unnamed: 0,State,Abbrev,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape1,Robbery,Aggravated assault,Propertycrime,Burglary,Larceny-theft,Arson2,Motor vehicletheft,Total,Per_1k
0,0,ALABAMA,AL,Abbeville,"2,551",18,0.0,2,0,16,49,14,33,NaN,2,134,52.52842023
1,1,ALABAMA,AL,Adamsville,"4,323",19,0.0,1,4,14,289,42,230,NaN,17,616,142.4936387
2,2,ALABAMA,AL,Alabaster,"33,501",92,0.0,2,10,80,579,56,497,NaN,26,"1,342",40.05850572
3,3,ALABAMA,AL,Albertville,"21,428",24,0.0,6,10,8,802,194,492,NaN,116,"1,652",77.09538921
4,4,ALABAMA,AL,Alexander City,"14,548",314,2.0,5,15,292,610,92,484,NaN,34,"1,848",127.0277701
5,5,ALABAMA,AL,Aliceville,"2,315",9,0.0,0,1,8,24,7,16,NaN,1,66,28.50971922
6,6,ALABAMA,AL,Andalusia,"8,753",82,1.0,6,6,69,467,76,368,NaN,23,"1,098",125.4427054
7,7,ALABAMA,AL,Anniston,"21,592",646,7.0,43,68,528,"1,696",413,"1,131",NaN,152,"4,684",216.9321971
8,8,ALABAMA,AL,Ardmore,"1,428",5,0.0,0,1,4,35,15,18,NaN,2,80,56.02240896
9,9,ALABAMA,AL,Ashford,"2,145",4,0.0,0,0,4,32,2,24,NaN,6,72,33.56643357
10,10,ALABAMA,AL,Ashland,"1,918",52,0.0,0,1,51,57,16,35,NaN,6,218,113.6600626
11,11,ALABAMA,AL,Athens,"26,177",13,3.0,0,8,2,768,110,630,NaN,28,"1,562",59.67070329
12,12,ALABAMA,AL,Auburn,"65,585",240,4.0,16,29,191,"1,396",115,"1,206",NaN,75,"3,272",49.88945643
13,13,ALABAMA,AL,Bay Minette,"9,304",73,0.0,3,3,67,250,35,196,NaN,19,646,69.43250215
14,14,ALABAMA,AL,Bayou La Batre,"2,500",36,0.0,4,5,27,305,70,203,NaN,32,682,272.8
15,15,ALABAMA,AL,Birmingham,"210,564","4,025",88.0,180,941,"2,816","13,295","2,555","8,988",145,"1,752","34,785",165.1991793
16,16,ALABAMA,AL,Boaz,"9,678",74,0.0,3,3,68,364,68,259,NaN,37,876,90.51456913
17,17,ALABAMA,AL,Brent,"4,853",18,0.0,2,2,14,96,25,66,NaN,5,228,46.98124871
18,18,ALABAMA,AL,Brewton,"5,212",31,0.0,3,1,27,175,19,132,NaN,24,412,79.04834996
19,19,ALABAMA,AL,Brilliant,867,3,0.0,0,0,3,29,7,19,NaN,3,64,73.8177624
20,20,ALABAMA,AL,Brookwood,"1,861",7,0.0,1,2,4,103,27,54,NaN,22,220,118.2160129
21,21,ALABAMA,AL,Calera,"14,334",265,2.0,10,6,247,429,164,242,NaN,23,"1,388",96.83270546
22,22,ALABAMA,AL,Camden,"1,824",26,1.0,1,0,24,85,28,55,NaN,2,222,121.7105263
23,23,ALABAMA,AL,Carrollton,961,4,0.0,0,0,4,13,4,7,NaN,2,34,35.3798127
24,24,ALABAMA,AL,Cedar Bluff,"1,794",1,0.0,0,0,1,20,3,16,NaN,1,42,23.41137124
25,25,ALABAMA,AL,Chatom,"1,200",8,0.0,0,0,8,34,5,25,NaN,4,84,70
26,26,ALABAMA,AL,Cherokee,999,1,0.0,0,0,1,19,2,13,NaN,4,40,40.04004004
27,27,ALABAMA,AL,Childersburg,"4,870",64,2.0,1,2,59,197,43,141,NaN,13,522,107.1868583
28,28,ALABAMA,AL,Clayton,"2,854",4,0.0,0,0,4,25,8,15,NaN,2,58,20.32235459
29,29,ALABAMA,AL,Coaling,"1,661",6,0.0,2,1,3,55,15,33,NaN,7,122,73.44972908
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9222,9222,WYOMING,WY,Casper,"58,200",117,2.0,60,4,51,"1,630",327,"1,165",5,138,3499,60.12027491
9223,9223,WYOMING,WY,Cheyenne,"64,178",207,2.0,30,23,152,"2,559",280,"2,063",10,216,5542,86.35357911
9224,9224,WYOMING,WY,Cody,"9,935",23,0.0,4,0,19,146,15,125,0,6,338,34.02113739
9225,9225,WYOMING,WY,Diamondville,761,0,0.0,0,0,0,0,0,0,0,0,0,0
9226,9226,WYOMING,WY,Douglas,"6,386",11,1.0,0,0,10,73,5,63,0,5,168,26.30754776
9227,9227,WYOMING,WY,Evanston,"11,797",11,0.0,3,1,7,212,11,193,0,8,446,37.80622192
9228,9228,WYOMING,WY,Evansville,"3,001",17,0.0,1,0,16,57,8,41,0,8,148,49.31689437
9229,9229,WYOMING,WY,Gillette,"30,659",56,0.0,13,3,40,667,83,561,2,23,1448,47.2291986
9230,9230,WYOMING,WY,Glenrock,"2,584",2,0.0,0,0,2,17,2,15,0,0,38,14.70588235
9231,9231,WYOMING,WY,Green River,"12,025",14,0.0,0,0,14,102,22,78,0,2,232,19.29313929
9232,9232,WYOMING,WY,Greybull,"1,864",9,0.0,1,0,8,10,5,4,0,1,38,20.38626609
9233,9233,WYOMING,WY,Hanna,787,0,0.0,0,0,0,6,2,4,0,0,12,15.24777637
9234,9234,WYOMING,WY,Kemmerer,"2,761",2,0.0,0,0,2,17,1,15,0,1,38,13.7631293
9235,9235,WYOMING,WY,Lander,"7,542",0,0.0,0,0,0,257,12,234,0,11,514,68.1516839
9236,9236,WYOMING,WY,Laramie,"32,509",32,1.0,8,1,22,395,44,332,6,19,860,26.45421268
9237,9237,WYOMING,WY,Lusk,"1,539",10,0.0,1,0,9,7,3,4,0,0,34,22.09226771
9238,9238,WYOMING,WY,Mills,"3,966",2,1.0,0,0,1,89,28,50,0,11,182,45.89006556
9239,9239,WYOMING,WY,Moorcroft,"1,060",1,0.0,0,0,1,9,0,9,0,0,20,18.86792453
9240,9240,WYOMING,WY,Newcastle,"3,370",14,0.0,4,0,10,39,6,27,0,6,106,31.45400593
9241,9241,WYOMING,WY,Pine Bluffs,"1,143",1,0.0,0,0,1,17,5,11,0,1,36,31.49606299
9242,9242,WYOMING,WY,Powell,"6,458",17,0.0,10,0,7,113,20,89,0,4,260,40.26014246
9243,9243,WYOMING,WY,Rawlins,"8,806",37,0.0,8,0,29,171,19,135,3,17,419,47.58119464
9244,9244,WYOMING,WY,Riverton,"11,076",26,0.0,5,7,14,332,29,278,1,25,717,64.73456121
9245,9245,WYOMING,WY,Rock Springs,"23,405",43,0.0,21,0,22,314,53,257,0,4,714,30.50630207
9246,9246,WYOMING,WY,Saratoga,"1,651",1,0.0,0,0,1,8,0,8,0,0,18,10.90248334
9247,9247,WYOMING,WY,Sheridan,"17,919",17,1.0,2,0,14,313,39,261,1,13,661,36.88821921
9248,9248,WYOMING,WY,Thermopolis,"2,919",13,0.0,0,0,13,64,10,48,0,6,154,52.75779376
9249,9249,WYOMING,WY,Torrington,"6,699",35,0.0,0,0,35,73,12,57,0,4,216,32.24361845
9250,9250,WYOMING,WY,Wheatland,"3,557",3,0.0,0,0,3,56,19,33,0,4,118,33.17402305
9251,9251,WYOMING,WY,Worland,"5,148",2,0.0,2,0,0,69,18,46,1,5,143,27.77777778

In [89]:
race

,metro_geocode,metro_geoname,metro_lon,metro_lat,metro_code,metro_total,metro_white,metro_hispanic,metro_black,metro_asian,metro_amind,metro_twoplus,City,State,County,Zip,Country,Source
0,35620,"New York-Newark-Jersey City, NY-NJ-PA",-74.08437,40.92033,6,100,46.34439,24.64721,15.80719,11.43804,0.17574,1.58744,New York,NY,New York County,10004.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
1,31080,"Los Angeles-Long Beach-Anaheim, CA",-118.14932,34.22097,6,100,29.47629,45.16830,6.44860,16.46581,0.18977,2.25123,Los Angeles,CA,La Salle County,78014.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
2,16980,"Chicago-Naperville-Elgin, IL-IN-WI",-87.96261,41.70249,6,100,52.59152,22.41137,16.32760,7.00777,0.12723,1.53452,Chicago,IL,Cook County,60601.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
3,19100,"Dallas-Fort Worth-Arlington, TX",-97.02543,32.81841,6,100,45.75036,29.04334,15.78827,7.26314,0.36657,1.78832,Dallas,TX,Dallas County,75201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
4,26420,"Houston-The Woodlands-Sugar Land, TX",-95.39950,29.78605,6,100,35.64306,37.63239,17.03209,8.00725,0.22344,1.46176,Houston,TX,Harris County,77001.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
5,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV",-77.47405,38.83342,6,100,45.07073,16.12978,25.07391,10.66850,0.21160,2.84548,Washington,DC,NaN,NaN,US,US Census Bureau
6,33100,"Miami-Fort Lauderdale-West Palm Beach, FL",-80.50479,26.15622,6,100,29.97581,45.83857,20.32081,2.58028,0.13672,1.14781,Miami,FL,Miami-Dade County,33231.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
7,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",-75.30339,39.90470,6,100,61.42822,9.70871,20.54679,6.22601,0.16064,1.92962,Philadelphia,PA,Philadelphia County,19019.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
8,12060,"Atlanta-Sandy Springs-Roswell, GA",-84.39952,33.69269,6,100,46.64287,10.87732,34.12094,6.22116,0.18829,1.94943,Atlanta,GA,Fulton County,30301.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
9,14460,"Boston-Cambridge-Newton, MA-NH",-71.10020,42.55728,3,100,70.14175,11.54695,7.88868,8.46736,0.14813,1.80712,Boston,MA,Suffolk County,2101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
10,38060,"Phoenix-Mesa-Scottsdale, AZ",-112.07055,33.18580,1,100,55.05535,31.19998,5.37923,4.27344,1.92601,2.16599,Phoenix,AZ,Maricopa County,85001.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
11,41860,"San Francisco-Oakland-Hayward, CA",-122.16705,37.78109,6,100,39.25676,21.86105,7.19580,27.60553,0.22717,3.85370,San Francisco,CA,San Francisco County,94101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
12,40140,"Riverside-San Bernardino-Ontario, CA",-116.12967,34.55170,6,100,31.52928,51.62665,7.09988,7.07593,0.43376,2.23451,Riverside,CA,Riverside County,92501.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
13,19820,"Detroit-Warren-Dearborn, MI",-83.23208,42.71913,2,100,66.19941,4.55670,22.11219,4.67638,0.29960,2.15572,Detroit,MI,Wayne County,48201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
14,42660,"Seattle-Tacoma-Bellevue, WA",-121.85418,47.55648,6,100,62.61025,10.21802,5.99272,15.55284,0.82270,4.80347,Seattle,WA,King County,98060.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
15,33460,"Minneapolis-St. Paul-Bloomington, MN-WI",-93.34557,45.06504,3,100,75.24687,5.98147,8.68224,6.94612,0.59484,2.54845,Minneapolis,MN,Hennepin County,55401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
16,41740,"San Diego-Carlsbad, CA",-116.73547,33.03388,6,100,45.20423,33.95825,4.70293,12.37801,0.43145,3.32512,San Diego,CA,San Diego County,92101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
17,45300,"Tampa-St. Petersburg-Clearwater, FL",-82.40829,28.15426,1,100,62.33860,20.04628,11.78930,3.64955,0.23983,1.93645,Tampa,FL,Hillsborough County,33601.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
18,19740,"Denver-Aurora-Lakewood, CO",-104.89496,39.43385,1,100,63.91493,23.19262,5.51607,4.53810,0.48803,2.35025,Denver,CO,Denver County,80202.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
19,41180,"St. Louis, MO-IL",-90.35019,38.73514,2,100,73.65114,3.12323,18.32751,2.74910,0.21219,1.93683,St. Louis,MO,St. Louis city,63101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
20,12580,"Baltimore-Columbia-Towson, MD",-76.57961,39.33718,2,100,56.17583,6.06214,29.21593,5.91835,0.24733,2.38041,Baltimore,MD,Baltimore city,21201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
21,36740,"Orlando-Kissimmee-Sanford, FL",-81.36320,28.43452,6,100,46.17729,31.47547,15.72926,4.58728,0.22628,1.80442,Orlando,FL,Orange County,32801.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
22,16740,"Charlotte-Concord-Gastonia, NC-SC",-80.86706,35.18901,2,100,60.68243,10.46861,22.57240,4.07027,0.34727,1.85901,Charlotte,NC,Mecklenburg County,28201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
23,41700,"San Antonio-New Braunfels, TX",-98.60216,29.42863,1,100,33.42808,55.60516,6.55463,2.70731,0.25448,1.45034,San Antonio,TX,Bexar County,78201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
24,38900,"Portland-Vancouver-Hillsboro, OR-WA",-122.47859,45.59817,3,100,72.83059,12.21114,2.99841,7.66323,0.69517,3.60145,Portland,OR,Multnomah County,97201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
25,40900,"Sacramento--Roseville--Arden-Arcade, CA",-120.99745,38.78034,6,100,51.79323,21.84222,6.99558,14.49248,0.54204,4.33445,Sacramento,CA,Sacramento County,94203.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
26,38300,"Pittsburgh, PA",-79.83104,40.43901,7,100,85.27162,1.81822,8.38897,2.60837,0.11760,1.79521,Pittsburgh,PA,Contra Costa County,94565.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
27,29820,"Las Vegas-Henderson-Paradise, NV",-115.01459,36.21513,6,100,42.19915,31.44610,11.66744,10.54616,0.45715,3.68401,Las Vegas,NV,Clark County,89101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
28,17140,"Cincinnati, OH-KY-IN",-84.42713,39.07160,7,100,79.11496,3.36740,12.53360,2.85133,0.15295,1.97977,Cincinnati,OH,Hamilton County,45201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
29,12420,"Austin-Round Rock, TX",-97.65448,30.26257,6,100,51.77815,32.65036,7.06636,6.28594,0.28229,1.93689,Austin,TX,Travis County,73301.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,12940,"Baton Rouge, LA",-91.13268,30.57116,2,100,56.44477,4.11230,35.80084,2.15082,0.25899,1.23227,Baton Rouge,LA,East Baton Rouge Parish,70801.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
71,35840,"North Port-Sarasota-Bradenton, FL",-82.32249,27.34777,7,100,77.19850,12.89283,6.34052,1.97426,0.19049,1.40341,North Port,FL,Tuscaloosa County,35473.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
72,19380,"Dayton, OH",-84.14203,39.82950,2,100,76.15405,2.88018,15.70595,2.46247,0.22764,2.56972,Dayton,OH,Montgomery County,45401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
73,16700,"Charleston-North Charleston, SC",-80.04338,33.04210,2,100,64.36876,5.69471,25.45138,2.09575,0.37746,2.01195,Charleston,SC,Charleston County,29401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
74,24660,"Greensboro-High Point, NC",-79.79155,36.02574,2,100,57.90356,8.58800,27.09952,4.04671,0.43545,1.92677,Greensboro,NC,Guilford County,27401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
75,15980,"Cape Coral-Fort Myers, FL",-81.84071,26.57793,1,100,66.81849,21.89648,8.08365,1.71241,0.21495,1.27404,Cape Coral,FL,Lee County,33904.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
76,44700,"Stockton-Lodi, CA",-121.27113,37.93459,6,100,31.04177,41.92743,7.10653,16.09000,0.43791,3.39635,Stockton,CA,San Joaquin County,95201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
77,30780,"Little Rock-North Little Rock-Conway, AR",-92.39722,34.75725,2,100,66.79548,5.40788,23.74093,1.77816,0.40413,1.87342,Little Rock,AR,Pulaski County,72201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
78,17820,"Colorado Springs, CO",-104.65833,38.84265,7,100,69.51697,17.09437,5.89061,3.14505,0.63672,3.71627,Colorado Springs,CO,NaN,NaN,US,US Census Bureau
79,14260,"Boise City, ID",-116.14315,43.01602,7,100,79.95499,13.84781,0.99011,2.28620,0.59445,2.32645,Boise,ID,Ada County,83701.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
80,29460,"Lakeland-Winter Haven, FL",-81.69736,27.94868,6,100,57.94884,23.61962,14.63188,1.90195,0.27316,1.62456,Lakeland,FL,Shelby County,38002.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
81,10420,"Akron, OH",-81.34942,41.14883,7,100,79.54898,2.16899,12.38074,3.46927,0.17280,2.25922,Akron,OH,Summit County,44301.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
82,36260,"Ogden-Clearfield, UT",-112.81593,41.43261,7,100,81.01625,13.11099,1.17040,2.14497,0.48262,2.07476,Ogden,UT,Weber County,84201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
83,49180,"Winston-Salem, NC",-80.34551,36.07623,2,100,67.91957,10.45385,17.76006,1.90675,0.31320,1.64657,Winston-Salem,NC,Daviess County,64689.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
84,31540,"Madison, WI",-89.59212,43.08010,7,100,81.86962,5.81295,4.49182,5.38474,0.30163,2.13924,Madison,WI,Dane County,53701.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
85,19660,"Deltona-Daytona Beach-Ormond Beach, FL",-81.21979,29.17403,7,100,71.79706,13.85102,10.29768,2.05138,0.28123,1.72164,Daytona Beach,FL,NaN,NaN,NaN,NaN
86,19780,"Des Moines-West Des Moines, IA",-93.94040,41.54780,7,100,80.28956,7.52111,5.51106,4.56036,0.17821,1.93970,Des Moines,IA,Polk County,50301.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
87,45060,"Syracuse, NY",-76.03362,43.15451,7,100,81.53980,4.34126,8.10021,2.96187,0.66718,2.38969,Syracuse,NY,Onondaga County,13201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
88,48620,"Wichita, KS",-97.39820,37.62506,7,100,71.80890,13.26602,7.30065,3.79957,0.80634,3.01851,Wichita,KS,Sedgwick County,67201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
89,39340,"Provo-Orem, UT",-112.35233,39.86453,7,100,82.22962,11.86365,0.58460,2.55756,0.45490,2.30968,Provo,UT,Butler County,42267.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
90,44140,"Springfield, MA",-72.64598,42.23017,1,100,67.25091,20.94400,6.50024,3.39891,0.15037,1.75557,Springfield,MA,Hampden County,1101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
91,12260,"Augusta-Richmond County, GA-SC",-81.98323,33.46099,2,100,54.41012,5.60160,35.29057,2.13914,0.32988,2.22869,Augusta,ME,Kennebec County,4330.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
92,45780,"Toledo, OH",-83.78176,41.49878,2,100,74.06974,7.04512,14.59981,1.67200,0.20767,2.40566,Toledo,OH,Lucas County,43601.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
93,37340,"Palm Bay-Melbourne-Titusville, FL",-80.73227,28.29348,7,100,74.07016,10.71645,9.96198,2.62127,0.31532,2.31482,Palm Bay,FL,Brevard County,32905.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
94,27140,"Jackson, MS",-90.22039,32.31733,2,100,46.09319,2.61253,48.99425,1.23740,0.13393,0.92870,Jackson,MS,Hinds County,39201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
95,20500,"Durham-Chapel Hill, NC",-79.09953,35.99098,2,100,54.69455,11.60542,26.04847,5.32766,0.30813,2.01577,Durham,NC,Durham County,27701.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
96,25420,"Harrisburg-Carlisle, PA",-77.10130,40.32659,7,100,76.32561,6.62880,10.20118,4.41584,0.16201,2.26656,Harrisburg,PA,Dauphin County,17101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
97,44060,"Spokane-Spokane Valley, WA",-117.57181,48.19372,7,100,84.54994,5.70173,1.73237,2.72488,1.76846,3.52262,Spokane,WA,Spokane County,99201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
98,16860,"Chattanooga, TN-GA",-85.35885,35.05192,2,100,78.12883,4.72081,13.54172,1.70544,0.27176,1.63144,Chattanooga,TN,Hamilton County,37401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
99,42540,"Scranton--Wilkes-Barre--Hazleton, PA",-75.89558,41.32306,7,100,82.63499,10.52720,3.47048,1.94803,0.11990,1.29941,Scranton,PA,Lackawanna County,18501.0,US,TIGER/Lineå¨ dataset from the US Census Bureau

In [90]:
police

,City,State,Abbrev,Latitude,Longitude,Per_1k,Population,Total
0,Abbeville,ALABAMA,AL,31.5718,-85.2505,3.136025,2551,8
1,Adamsville,ALABAMA,AL,33.6009,-86.9561,6.708304,4323,29
2,Addison,ALABAMA,AL,34.2023,-87.1814,6.896552,725,5
3,Alabaster,ALABAMA,AL,33.2443,-86.8164,2.507388,33501,84
4,Alexander City,ALABAMA,AL,32.9440,-85.9539,4.536706,14548,66
5,Aliceville,ALABAMA,AL,33.1296,-88.1514,3.023758,2315,7
6,Altoona,ALABAMA,AL,34.0262,-86.3261,2.188184,914,2
7,Andalusia,ALABAMA,AL,31.3085,-86.4832,4.341369,8753,38
8,Anderson,ALABAMA,AL,34.9248,-87.2687,3.636364,275,1
9,Anniston,ALABAMA,AL,33.6594,-85.8316,4.168210,21592,90
10,Arab,ALABAMA,AL,34.3181,-86.4958,4.090964,8311,34
11,Ardmore,ALABAMA,AL,34.9900,-86.8500,7.002801,1428,10
12,Argo,ALABAMA,AL,33.6818,-86.5305,2.094972,4296,9
13,Arley,ALABAMA,AL,34.0800,-87.2126,5.813953,344,2
14,Ashford,ALABAMA,AL,31.1830,-85.2363,2.797203,2145,6
15,Ashland,ALABAMA,AL,33.2737,-85.8361,7.299270,1918,14
16,Ashville,ALABAMA,AL,33.8369,-86.2550,2.172024,2302,5
17,Athens,ALABAMA,AL,34.8029,-86.9717,2.253887,26177,59
18,Atmore,ALABAMA,AL,31.0238,-87.4939,3.655936,9847,36
19,Attalla,ALABAMA,AL,34.0218,-86.0886,5.002588,5797,29
20,Auburn,ALABAMA,AL,32.6099,-85.4808,2.180377,65585,143
21,Autaugaville,ALABAMA,AL,32.4340,-86.6547,1.173709,852,1
22,Baker Hill,ALABAMA,AL,NaN,NaN,11.904762,252,3
23,Bay Minette,ALABAMA,AL,30.8830,-87.7730,3.224420,9304,30
24,Bayou La Batre,ALABAMA,AL,30.4169,-88.2250,8.000000,2500,20
25,Bear Creek,ALABAMA,AL,34.2748,-87.7006,1.926782,1038,2
26,Berry,ALABAMA,AL,33.6598,-87.6000,4.578755,1092,5
27,Bessemer,ALABAMA,AL,33.4018,-86.9544,6.059451,26240,159
28,Birmingham,ALABAMA,AL,33.5207,-86.8024,4.639919,210564,977
29,Blountsville,ALABAMA,AL,34.0815,-86.5911,4.196643,1668,7
...,...,...,...,...,...,...,...,...
9111,Cody,WYOMING,WY,44.5263,-109.0564,2.415702,9935,24
9112,Diamondville,WYOMING,WY,41.7794,-110.5385,2.628121,761,2
9113,Douglas,WYOMING,WY,42.7597,-105.3822,2.975258,6386,19
9114,Evanston,WYOMING,WY,41.2680,-110.9633,2.543019,11797,30
9115,Evansville,WYOMING,WY,42.8500,-106.2500,3.998667,3001,12
9116,Gillette,WYOMING,WY,44.2906,-105.5019,2.609348,30659,80
9117,Glenrock,WYOMING,WY,42.8612,-105.8725,4.256966,2584,11
9118,Green River,WYOMING,WY,41.5291,-109.4665,2.744283,12025,33
9119,Greybull,WYOMING,WY,44.4892,-108.0562,3.218884,1864,6
9120,Hanna,WYOMING,WY,41.8700,-106.5620,2.541296,787,2
9121,Jackson,WYOMING,WY,43.4800,-110.7618,3.748477,10671,40
9122,Kemmerer,WYOMING,WY,41.7925,-110.5377,2.173126,2761,6
9123,Lander,WYOMING,WY,42.8331,-108.7307,2.651816,7542,20
9124,Laramie,WYOMING,WY,41.3114,-105.5911,2.214771,32509,72
9125,Lusk,WYOMING,WY,42.7625,-104.4522,3.898635,1539,6
9126,Mills,WYOMING,WY,42.8405,-106.3659,5.295008,3966,21
9127,Moorcroft,WYOMING,WY,44.2633,-104.9503,3.773585,1060,4
9128,Newcastle,WYOMING,WY,43.8547,-104.2049,4.747774,3370,16
9129,Pine Bluffs,WYOMING,WY,41.1803,-104.0663,1.749781,1143,2
9130,Powell,WYOMING,WY,44.7529,-108.7590,3.716321,6458,24
9131,Rawlins,WYOMING,WY,41.7911,-107.2387,3.066091,8806,27
9132,Riverton,WYOMING,WY,43.0250,-108.3799,2.166847,11076,24
9133,Rock Springs,WYOMING,WY,41.5869,-109.2048,2.392651,23405,56
9134,Saratoga,WYOMING,WY,41.4550,-106.8064,4.845548,1651,8
9135,Sheridan,WYOMING,WY,44.7948,-106.8223,2.455494,17919,44
9136,Sundance,WYOMING,WY,44.4064,-104.3758,2.351097,1276,3
9137,Thermopolis,WYOMING,WY,43.6461,-108.2120,4.453580,2919,13
9138,Torrington,WYOMING,WY,42.0625,-104.1844,3.582624,6699,24
9139,Wheatland,WYOMING,WY,42.0544,-104.9527,2.811358,3557,10
9140,Worland,WYOMING,WY,44.0169,-107.9558,2.525253,5148,13

In [91]:
income

,id,Name,Metro-Label,City,State,Median_Income
0,310M400US31060,"Los Alamos, NM Micro Area",Los Alamos,Los Alamos,NM,139944
1,310M400US47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",Washington-Arlington-Alexandria,Washington,DC,108625
2,310M400US41940,"San Jose-Sunnyvale-Santa Clara, CA Metro Area",San Jose-Sunnyvale-Santa Clara,San Jose,CA,108333
3,310M400US20780,"Edwards, CO Micro Area",Edwards,Edwards,CO,105173
4,310M400US27940,"Juneau, AK Micro Area",Juneau,Juneau,AK,105026
5,310M400US41860,"San Francisco-Oakland-Hayward, CA Metro Area",San Francisco-Oakland-Hayward,San Francisco,CA,104194
6,310M400US44920,"Summit Park, UT Micro Area",Summit Park,Summit Park,UT,103235
7,310M400US14860,"Bridgeport-Stamford-Norwalk, CT Metro Area",Bridgeport-Stamford-Norwalk,Bridgeport,CT,101381
8,310M400US14720,"Breckenridge, CO Micro Area",Breckenridge,Breckenridge,CO,97958
9,310M400US27220,"Jackson, WY-ID Micro Area",Jackson,Jackson,WY,97074
10,310M400US48780,"Williston, ND Micro Area",Williston,Williston,ND,96331
11,310M400US14500,"Boulder, CO Metro Area",Boulder,Boulder,CO,95149
12,310M400US34900,"Napa, CA Metro Area",Napa,Napa,CA,94765
13,310M400US25720,"Heber, UT Micro Area",Heber,Heber,UT,91112
14,310M400US47240,"Vineyard Haven, MA Micro Area",Vineyard Haven,Vineyard Haven,MA,89375
15,310M400US14460,"Boston-Cambridge-Newton, MA-NH Metro Area",Boston-Cambridge-Newton,Boston,MA,89184
16,310M400US19860,"Dickinson, ND Micro Area",Dickinson,Dickinson,ND,88944
17,310M400US42660,"Seattle-Tacoma-Bellevue, WA Metro Area",Seattle-Tacoma-Bellevue,Seattle,WA,88843
18,310M400US45940,"Trenton, NJ Metro Area",Trenton,Trenton,NJ,88764
19,310M400US42220,"Santa Rosa, CA Metro Area",Santa Rosa,Santa Rosa,CA,87899
20,310M400US42100,"Santa Cruz-Watsonville, CA Metro Area",Santa Cruz-Watsonville,Santa Cruz,CA,87873
21,310M400US33260,"Midland, TX Metro Area",Midland,Midland,TX,87748
22,310M400US11260,"Anchorage, AK Metro Area",Anchorage,Anchorage,AK,87661
23,310M400US37100,"Oxnard-Thousand Oaks-Ventura, CA Metro Area",Oxnard-Thousand Oaks-Ventura,Oxnard,CA,86445
24,310M400US15680,"California-Lexington Park, MD Metro Area",California-Lexington Park,California,MD,86389
25,310M400US20420,"Durango, CO Micro Area",Durango,Durango,CO,85213
26,310M400US45860,"Torrington, CT Micro Area",Torrington,Torrington,CT,84930
27,310M400US12580,"Baltimore-Columbia-Towson, MD Metro Area",Baltimore-Columbia-Towson,Baltimore,MD,84710
28,310M400US23940,"Gillette, WY Micro Area",Gillette,Gillette,WY,84641
29,310M400US25540,"Hartford-West Hartford-East Hartford, CT Metro...",Hartford-West Hartford-East Hartford,Hartford,CT,84411
...,...,...,...,...,...,...
914,310M400US32620,"McComb, MS Micro Area",McComb,McComb,MS,38667
915,310M400US36660,"Opelousas, LA Micro Area",Opelousas,Opelousas,LA,37685
916,310M400US17500,"Clewiston, FL Micro Area",Clewiston,Clewiston,FL,37254
917,310M400US15180,"Brownsville-Harlingen, TX Metro Area",Brownsville-Harlingen,Brownsville,TX,37251
918,310M400US26940,"Indianola, MS Micro Area",Indianola,Indianola,MS,37071
919,310M400US17260,"Clarksdale, MS Micro Area",Clarksdale,Clarksdale,MS,37070
920,310M400US31300,"Lumberton, NC Micro Area",Lumberton,Lumberton,NC,36867
921,310M400US29700,"Laredo, TX Metro Area",Laredo,Laredo,TX,35322
922,310M400US25760,"Helena-West Helena, AR Micro Area",Helena-West Helena,Helena,AR,35260
923,310M400US32580,"McAllen-Edinburg-Mission, TX Metro Area",McAllen-Edinburg-Mission,McAllen,TX,35102
924,310M400US23700,"Gallup, NM Micro Area",Gallup,Gallup,NM,34311
925,310M400US19700,"Deming, NM Micro Area",Deming,Deming,NM,33724
926,310M400US22340,"Fitzgerald, GA Micro Area",Fitzgerald,Fitzgerald,GA,32581
927,310M400US39940,"Rexburg, ID Micro Area",Rexburg,Rexburg,ID,29628
928,310M400US20580,"Eagle Pass, TX Micro Area",Eagle Pass,Eagle Pass,TX,27460
929,310M400US33180,"Middlesborough, KY Micro Area",Middlesborough,Middlesborough,KY,27203
930,310M400US41980,"San Juan-Carolina-Caguas, PR Metro Area",San Juan-Carolina-Caguas,San Juan,PR,23010
931,310M400US40100,"Rio Grande City, TX Micro Area",Rio Grande City,Rio Grande City,TX,22935
932,310M400US39700,"Raymondville, TX Micro Area",Raymondville,Raymondville,TX,22391
933,310M400US17620,"Coamo, PR Micro Area",Coamo,Coamo,PR,21714
934,310M400US11640,"Arecibo, PR Metro Area",Arecibo,Arecibo,PR,18990
935,310M400US32420,"Mayagï¿½ez, PR Metro Area",Mayagï¿½ez,Mayagï¿½ez,PR,18784
936,310M400US25020,"Guayama, PR Metro Area",Guayama,Guayama,PR,18273
937,310M400US38660,"Ponce, PR Metro Area",Ponce,Ponce,PR,18247
938,310M400US41900,"San Germï¿½n, PR Metro Area",San Germï¿½n,San Germï¿½n,PR,18088
939,310M400US17640,"Coco, PR Micro Area",Coco,Coco,PR,17974
940,310M400US42180,"Santa Isabel, PR Micro Area",Santa Isabel,Santa Isabel,PR,17650
941,310M400US10380,"Aguadilla-Isabela, PR Metro Area",Aguadilla-Isabela,Aguadilla,PR,17307
942,310M400US27580,"Jayuya, PR Micro Area",Jayuya,Jayuya,PR,16713
943,310M400US10260,"Adjuntas, PR Micro Area",Adjuntas,Adjuntas,PR,11989

In [92]:
cities = np.array(race['City'])
states = np.array(race['State'])
cities
cities

array(['New York', 'Los Angeles', 'Chicago', 'Dallas', 'Houston',
       'Washington', 'Miami', 'Philadelphia', 'Atlanta', 'Boston',
       'Phoenix', 'San Francisco', 'Riverside', 'Detroit', 'Seattle',
       'Minneapolis', 'San Diego', 'Tampa', 'Denver', 'St. Louis',
       'Baltimore', 'Orlando', 'Charlotte', 'San Antonio', 'Portland',
       'Sacramento', 'Pittsburgh', 'Las Vegas', 'Cincinnati', 'Austin',
       'Kansas City', 'Columbus', 'Cleveland', 'Indianapolis', 'San Jose',
       'Nashville', 'Virginia Beach', 'Providence', 'Milwaukee',
       'Jacksonville', 'Oklahoma City', 'Raleigh', 'Memphis', 'Richmond',
       'Louisville', 'New Orleans', 'Salt Lake City', 'Hartford',
       'Birmingham', 'Buffalo', 'Rochester', 'Grand Rapids', 'Tucson',
       'Fresno', 'Tulsa', 'Honolulu', 'Worcester', 'Bridgeport', 'Omaha',
       'Albuquerque', 'Greenville', 'Bakersfield', 'Knoxville', 'Albany',
       'McAllen', 'New Haven', 'Oxnard', 'El Paso', 'Allentown',
       'Columbia', 'Baton Rouge', 'North Port', 'Dayton', 'Charleston',
       'Greensboro', 'Cape Coral', 'Stockton', 'Little Rock',
       'Colorado Springs', 'Boise', 'Lakeland', 'Akron', 'Ogden',
       'Winston-Salem', 'Madison', 'Daytona Beach', 'Des Moines',
       'Syracuse', 'Wichita', 'Provo', 'Springfield', 'Augusta', 'Toledo',
       'Palm Bay', 'Jackson', 'Durham', 'Harrisburg', 'Spokane',
       'Chattanooga', 'Scranton'], dtype=object)

In [93]:
from string import digits

remove_digits = str.maketrans('', '', digits)

offenses['City'] = offenses['City'].apply(lambda x: str(x).translate(remove_digits))
police['City'] = police['City'].apply(lambda x: x.translate(remove_digits))
offenses['Abbrev'] = offenses['Abbrev'].apply(lambda x: str(x))

In [94]:
police_vals = []
offenses_vals = []
incomes_vals = []
for i in range(len(cities)):
    city = cities[i]
    state = states[i]
    print(city)
    print(state)
    police_row = police[(police.Abbrev == state) & (police.City == city)]
    offenses_row = offenses[(offenses.Abbrev == state) & (offenses.City == city)]
    income_row = income[(income.State == state) & (income.City == city)]
    if city == "Albuquerque" or city == "Jackson":
        temp = 0
    else:
        temp = police_row.Per_1k.values[0]
    police_vals.append(temp)
    if city == "Raleigh" or city == "Louisville" or city == "Winston-Salem" or state == "IA":
        temp2 = 0
    else:
        temp2 = offenses_row.Per_1k.values[0]
    offenses_vals.append(temp2)
    temp3 = income_row.Median_Income.values[0]
    incomes_vals.append(temp3)

New York
NY
Los Angeles
CA
Chicago
IL
Dallas
TX
Houston
TX
Washington
DC
Miami
FL
Philadelphia
PA
Atlanta
GA
Boston
MA
Phoenix
AZ
San Francisco
CA
Riverside
CA
Detroit
MI
Seattle
WA
Minneapolis
MN
San Diego
CA
Tampa
FL
Denver
CO
St. Louis
MO
Baltimore
MD
Orlando
FL
Charlotte
NC
San Antonio
TX
Portland
OR
Sacramento
CA
Pittsburgh
PA
Las Vegas
NV
Cincinnati
OH
Austin
TX
Kansas City
MO
Columbus
OH
Cleveland
OH
Indianapolis
IN
San Jose
CA
Nashville
TN
Virginia Beach
VA
Providence
RI
Milwaukee
WI
Jacksonville
FL
Oklahoma City
OK
Raleigh
NC
Memphis
TN
Richmond
VA
Louisville
KY
New Orleans
LA
Salt Lake City
UT
Hartford
CT
Birmingham
AL
Buffalo
NY
Rochester
NY
Grand Rapids
MI
Tucson
AZ
Fresno
CA
Tulsa
OK
Honolulu
HI
Worcester
MA
Bridgeport
CT
Omaha
NE
Albuquerque
NM
Greenville
NC
Bakersfield
CA
Knoxville
TN
Albany
NY
McAllen
TX
New Haven
CT
Oxnard
CA
El Paso
TX
Allentown
PA
Columbia
SC
Baton Rouge
LA
North Port
FL
Dayton
OH
Charleston
SC
Greensboro
NC
Cape Coral
FL
Stockton
CA
Little Rock
AR
Colorado Springs
CO
Boise
ID
Lakeland
FL
Akron
OH
Ogden
UT
Winston-Salem
NC
Madison
WI
Daytona Beach
FL
Des Moines
IA
Syracuse
NY
Wichita
KS
Provo
UT
Springfield
MA
Augusta
ME
Toledo
OH
Palm Bay
FL
Jackson
MS
Durham
NC
Harrisburg
PA
Spokane
WA
Chattanooga
TN
Scranton
PA

In [96]:
len(police_vals)

100

In [97]:
race["police_per_1k"] = police_vals
race["offenses_per_1k"] = offenses_vals
race["median_income"] = incomes_vals
race

,metro_geocode,metro_geoname,metro_lon,metro_lat,metro_code,metro_total,metro_white,metro_hispanic,metro_black,metro_asian,...,metro_twoplus,City,State,County,Zip,Country,Source,police_per_1k,offenses_per_1k,median_income
0,35620,"New York-Newark-Jersey City, NY-NJ-PA",-74.08437,40.92033,6,100,46.34439,24.64721,15.80719,11.43804,...,1.58744,New York,NY,New York County,10004.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,6.133633,40.86835756,77003
1,31080,"Los Angeles-Long Beach-Anaheim, CA",-118.14932,34.22097,6,100,29.47629,45.16830,6.44860,16.46581,...,2.25123,Los Angeles,CA,La Salle County,78014.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.228495,65.6220834,71074
2,16980,"Chicago-Naperville-Elgin, IL-IN-WI",-87.96261,41.70249,6,100,52.59152,22.41137,16.32760,7.00777,...,1.53452,Chicago,IL,Cook County,60601.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,5.180293,83.91516323,74605
3,19100,"Dallas-Fort Worth-Arlington, TX",-97.02543,32.81841,6,100,45.75036,29.04334,15.78827,7.26314,...,1.78832,Dallas,TX,Dallas County,75201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.628324,80.42261636,73537
4,26420,"Houston-The Woodlands-Sugar Land, TX",-95.39950,29.78605,6,100,35.64306,37.63239,17.03209,8.00725,...,1.46176,Houston,TX,Harris County,77001.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.668695,100.7221427,70362
5,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV",-77.47405,38.83342,6,100,45.07073,16.12978,25.07391,10.66850,...,2.84548,Washington,DC,NaN,NaN,US,US Census Bureau,6.434576,104.2230463,108625
6,33100,"Miami-Fort Lauderdale-West Palm Beach, FL",-80.50479,26.15622,6,100,29.97581,45.83857,20.32081,2.58028,...,1.14781,Miami,FL,Miami-Dade County,33231.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.680395,83.89441218,56534
7,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",-75.30339,39.90470,6,100,61.42822,9.70871,20.54679,6.22601,...,1.92962,Philadelphia,PA,Philadelphia County,19019.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,4.641708,80.38232647,75330
8,12060,"Atlanta-Sandy Springs-Roswell, GA",-84.39952,33.69269,6,100,46.64287,10.87732,34.12094,6.22116,...,1.94943,Atlanta,GA,Fulton County,30301.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,4.005192,108.6461361,69612
9,14460,"Boston-Cambridge-Newton, MA-NH",-71.10020,42.55728,3,100,70.14175,11.54695,7.88868,8.46736,...,1.80712,Boston,MA,Suffolk County,2101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.908314,52.77591039,89184
10,38060,"Phoenix-Mesa-Scottsdale, AZ",-112.07055,33.18580,1,100,55.05535,31.19998,5.37923,4.27344,...,2.16599,Phoenix,AZ,Maricopa County,85001.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.360442,84.64563119,67192
11,41860,"San Francisco-Oakland-Hayward, CA",-122.16705,37.78109,6,100,39.25676,21.86105,7.19580,27.60553,...,3.85370,San Francisco,CA,San Francisco County,94101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.275676,124.8242965,104194
12,40140,"Riverside-San Bernardino-Ontario, CA",-116.12967,34.55170,6,100,31.52928,51.62665,7.09988,7.07593,...,2.23451,Riverside,CA,Riverside County,92501.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.576934,72.19157639,61903
13,19820,"Detroit-Warren-Dearborn, MI",-83.23208,42.71913,2,100,66.19941,4.55670,22.11219,4.67638,...,2.15572,Detroit,MI,Wayne County,48201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,4.497412,127.5229973,64665
14,42660,"Seattle-Tacoma-Bellevue, WA",-121.85418,47.55648,6,100,62.61025,10.21802,5.99272,15.55284,...,4.80347,Seattle,WA,King County,98060.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.630732,116.7336915,88843
15,33460,"Minneapolis-St. Paul-Bloomington, MN-WI",-93.34557,45.06504,3,100,75.24687,5.98147,8.68224,6.94612,...,2.54845,Minneapolis,MN,Hennepin County,55401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.421421,94.25560581,84210
16,41740,"San Diego-Carlsbad, CA",-116.73547,33.03388,6,100,45.20423,33.95825,4.70293,12.37801,...,3.32512,San Diego,CA,San Diego County,92101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.623396,45.7634729,79436
17,45300,"Tampa-St. Petersburg-Clearwater, FL",-82.40829,28.15426,1,100,62.33860,20.04628,11.78930,3.64955,...,1.93645,Tampa,FL,Hillsborough County,33601.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.069132,41.70812709,59054
18,19740,"Denver-Aurora-Lakewood, CO",-104.89496,39.43385,1,100,63.91493,23.19262,5.51607,4.53810,...,2.35025,Denver,CO,Denver County,80202.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.530715,88.19762884,84176
19,41180,"St. Louis, MO-IL",-90.35019,38.73514,2,100,73.65114,3.12323,18.32751,2.74910,...,1.93683,St. Louis,MO,St. Louis city,63101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,5.239919,154.8578411,67295
20,12580,"Baltimore-Columbia-Towson, MD",-76.57961,39.33718,2,100,56.17583,6.06214,29.21593,5.91835,...,2.38041,Baltimore,MD,Baltimore city,21201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,4.847746,126.8044847,84710
21,36740,"Orlando-Kissimmee-Sanford, FL",-81.36320,28.43452,6,100,46.17729,31.47547,15.72926,4.58728,...,1.80442,Orlando,FL,Orange County,32801.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.292882,112.2614492,59050
22,16740,"Charlotte-Concord-Gastonia, NC-SC",-80.86706,35.18901,2,100,60.68243,10.46861,22.57240,4.07027,...,1.85901,Charlotte,NC,Mecklenburg County,28201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.514940,81.7699077,64840
23,41700,"San Antonio-New Braunfels, TX",-98.60216,29.42863,1,100,33.42808,55.60516,6.55463,2.70731,...,1.45034,San Antonio,TX,Bexar County,78201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.943056,92.53128638,63562
24,38900,"Portland-Vancouver-Hillsboro, OR-WA",-122.47859,45.59817,3,100,72.83059,12.21114,2.99841,7.66323,...,3.60145,Portland,OR,Multnomah County,97201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.790768,119.5934638,76453
25,40900,"Sacramento--Roseville--Arden-Arcade, CA",-120.99745,38.78034,6,100,51.79323,21.84222,6.99558,14.49248,...,4.33445,Sacramento,CA,Sacramento County,94203.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.869686,74.23126912,76325
26,38300,"Pittsburgh, PA",-79.83104,40.43901,7,100,85.27162,1.81822,8.38897,2.60837,...,1.79521,Pittsburgh,PA,Contra Costa County,94565.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.301999,72.23412132,65487
27,29820,"Las Vegas-Henderson-Paradise, NV",-115.01459,36.21513,6,100,42.19915,31.44610,11.66744,10.54616,...,3.68401,Las Vegas,NV,Clark County,89101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.757862,68.91734929,61465
28,17140,"Cincinnati, OH-KY-IN",-84.42713,39.07160,7,100,79.11496,3.36740,12.53360,2.85133,...,1.97977,Cincinnati,OH,Hamilton County,45201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.864853,107.5998834,67953
29,12420,"Austin-Round Rock, TX",-97.65448,30.26257,6,100,51.77815,32.65036,7.06636,6.28594,...,1.93689,Austin,TX,Travis County,73301.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.488329,76.85463721,82689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,12940,"Baton Rouge, LA",-91.13268,30.57116,2,100,56.44477,4.11230,35.80084,2.15082,...,1.23227,Baton Rouge,LA,East Baton Rouge Parish,70801.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.536634,125.5260465,63944
71,35840,"North Port-Sarasota-Bradenton, FL",-82.32249,27.34777,7,100,77.19850,12.89283,6.34052,1.97426,...,1.40341,North Port,FL,Tuscaloosa County,35473.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.068497,38.50359032,67975
72,19380,"Dayton, OH",-84.14203,39.82950,2,100,76.15405,2.88018,15.70595,2.46247,...,2.56972,Dayton,OH,Montgomery County,45401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.026539,109.0125202,63557
73,16700,"Charleston-North Charleston, SC",-80.04338,33.04210,2,100,64.36876,5.69471,25.45138,2.09575,...,2.01195,Charleston,SC,Charleston County,29401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.749307,47.66142444,69677
74,24660,"Greensboro-High Point, NC",-79.79155,36.02574,2,100,57.90356,8.58800,27.09952,4.04671,...,1.92677,Greensboro,NC,Guilford County,27401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.662821,73.36565541,56093
75,15980,"Cape Coral-Fort Myers, FL",-81.84071,26.57793,1,100,66.81849,21.89648,8.08365,1.71241,...,1.27404,Cape Coral,FL,Lee County,33904.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.655409,31.6071305,64089
76,44700,"Stockton-Lodi, CA",-121.27113,37.93459,6,100,31.04177,41.92743,7.10653,16.09000,...,3.39635,Stockton,CA,San Joaquin County,95201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.142688,103.9634945,61064
77,30780,"Little Rock-North Little Rock-Conway, AR",-92.39722,34.75725,2,100,66.79548,5.40788,23.74093,1.77816,...,1.87342,Little Rock,AR,Pulaski County,72201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.517522,160.1651881,61437
78,17820,"Colorado Springs, CO",-104.65833,38.84265,7,100,69.51697,17.09437,5.89061,3.14505,...,3.71627,Colorado Springs,CO,NaN,NaN,US,US Census Bureau,2.111971,78.24691589,72846
79,14260,"Boise City, ID",-116.14315,43.01602,7,100,79.95499,13.84781,0.99011,2.28620,...,2.32645,Boise,ID,Ada County,83701.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.640024,46.07768303,64468
80,29460,"Lakeland-Winter Haven, FL",-81.69736,27.94868,6,100,57.94884,23.61962,14.63188,1.90195,...,1.62456,Lakeland,FL,Shelby County,38002.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.202087,68.93154284,52649
81,10420,"Akron, OH",-81.34942,41.14883,7,100,79.54898,2.16899,12.38074,3.46927,...,2.25922,Akron,OH,Summit County,44301.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.402752,90.08042895,64126
82,36260,"Ogden-Clearfield, UT",-112.81593,41.43261,7,100,81.01625,13.11099,1.17040,2.14497,...,2.07476,Ogden,UT,Weber County,84201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.985939,83.0898466,69472
83,49180,"Winston-Salem, NC",-80.34551,36.07623,2,100,67.91957,10.45385,17.76006,1.90675,...,1.64657,Winston-Salem,NC,Daviess County,64689.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.780040,0,57049
84,31540,"Madison, WI",-89.59212,43.08010,7,100,81.86962,5.81295,4.49182,5.38474,...,2.13924,Madison,WI,Dane County,53701.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.302142,60.14973593,80472
85,19660,"Deltona-Daytona Beach-Ormond Beach, FL",-81.21979,29.17403,7,100,71.79706,13.85102,10.29768,2.05138,...,1.72164,Daytona Beach,FL,NaN,NaN,NaN,NaN,4.230045,119.5277416,56253
86,19780,"Des Moines-West Des Moines, IA",-93.94040,41.54780,7,100,80.28956,7.52111,5.51106,4.56036,...,1.93970,Des Moines,IA,Polk County,50301.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.329033,0,75304
87,45060,"Syracuse, NY",-76.03362,43.15451,7,100,81.53980,4.34126,8.10021,2.96187,...,2.38969,Syracuse,NY,Onondaga County,13201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.409512,76.06424973,66311
88,48620,"Wichita, KS",-97.39820,37.62506,7,100,71.80890,13.26602,7.30065,3.79957,...,3.01851,Wichita,KS,Sedgwick County,67201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.103511,136.3325386,63726
89,39340,"Provo-Orem, UT",-112.35233,39.86453,7,100,82.22962,11.86365,0.58460,2.55756,...,2.30968,Provo,UT,Butler County,42267.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.076399,38.96224976,58522
90,44140,"Springfield, MA",-72.64598,42.23017,1,100,67.25091,20.94400,6.50024,3.39891,...,1.75557,Springfield,MA,Hampden County,1101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.557182,72.60002964,64488
91,12260,"Augusta-Richmond County, GA-SC",-81.98323,33.46099,2,100,54.41012,5.60160,35.29057,2.13914,...,2.22869,Augusta,ME,Kennebec County,4330.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.185229,73.20628408,62659
92,45780,"Toledo, OH",-83.78176,41.49878,2,100,74.06974,7.04512,14.59981,1.67200,...,2.40566,Toledo,OH,Lucas County,43601.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.494337,91.30145479,59234
93,37340,"Palm Bay-Melbourne-Titusville, FL",-80.73227,28.29348,7,100,74.07016,10.71645,9.96198,2.62127,...,2.31482,Palm Bay,FL,Brevard County,32905.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.851163,44.57848399,62318
94,27140,"Jackson, MS",-90.22039,32.31733,2,100,46.09319,2.61253,48.99425,1.23740,...,0.92870,Jackson,MS,Hinds County,39201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,0.000000,102.009348,59823
95,20500,"Durham-Chapel Hill, NC",-79.09953,35.99098,2,100,54.69455,11.60542,26.04847,5.32766,...,2.01577,Durham,NC,Durham County,27701.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.341476,78.26592002,75727
96,25420,"Harrisburg-Carlisle, PA",-77.10130,40.32659,7,100,76.32561,6.62880,10.20118,4.41584,...,2.26656,Harrisburg,PA,Dauphin County,17101.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.418316,73.00547338,70981
97,44060,"Spokane-Spokane Valley, WA",-117.57181,48.19372,7,100,84.54994,5.70173,1.73237,2.72488,...,3.52262,Spokane,WA,Spokane County,99201.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,1.878821,157.6697125,63801
98,16860,"Chattanooga, TN-GA",-85.35885,35.05192,2,100,78.12883,4.72081,13.54172,1.70544,...,1.63144,Chattanooga,TN,Hamilton County,37401.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,3.331541,142.2418333,59763
99,42540,"Scranton--Wilkes-Barre--Hazleton, PA",-75.89558,41.32306,7,100,82.63499,10.52720,3.47048,1.94803,...,1.29941,Scranton,PA,Lackawanna County,18501.0,US,TIGER/Lineå¨ dataset from the US Census Bureau,2.184332,59.7479024,57361

In [98]:
race.to_csv('race_comparison.csv')

In [22]:
cities

array(['New York', 'Los Angeles', 'Chicago', 'Dallas', 'Houston',
       'Washington', 'Miami', 'Philadelphia', 'Atlanta', 'Boston',
       'Phoenix', 'San Francisco', 'Riverside', 'Detroit', 'Seattle',
       'Minneapolis', 'San Diego', 'Tampa', 'Denver', 'Saint Louis',
       'Baltimore', 'Orlando', 'Charlotte', 'San Antonio', 'Portland',
       'Sacramento', 'Pittsburg', 'Las Vegas', 'Cincinnati', 'Austin',
       'Kansas City', 'Columbia', 'Cleveland', 'Indianapolis', 'San Jose',
       'Nashville', 'Virginia Beach', 'Providence', 'Milwaukee',
       'Jacksonville', 'Oklahoma City', 'Raleigh', 'Memphis', 'Richmond',
       'Louisville', 'New Orleans', 'Salt Lake City', 'Hartford',
       'Birmingham', 'Buffalo', 'Rochester', 'Grand Rapids', 'Tucson',
       'Fresno', 'Tulsa', 'Honolulu', 'Worcester', 'Bridgeport', 'Omaha',
       'Albuquerque', 'Greenville', 'Bakersfield', 'Knoxville', 'Albany',
       'McAllen', 'New Haven', 'Oxnard', 'El Paso', 'Allentown',
       'Columbia', 'Baton Rouge', 'Northport', 'Dayton', 'Charleston',
       'Greensboro', 'Cape Coral', 'Stockton', 'Little Rock',
       'Colorado Springs', 'Boise City', 'Lakeland', 'Akron', 'Ogden',
       'Winston', 'Madison', 'Daytona Beach', 'Des Moines', 'Syracuse',
       'Wichita', 'Provo', 'Springfield', 'Augusta', 'Toledo', 'Palm Bay',
       'Jackson', 'Durham', 'Harrisburg', 'Spokane', 'Chattanooga',
       'Scranton'], dtype=object)

In [25]:
offenses[(offenses.Abbrev == state) & (offenses.City == city)]

,State,Abbrev,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape1,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Arson2,Motor vehicle theft,Total,Per_1k
5346,NEW YORK,NY,New York,"8,523,171","46,113",295.0,"2,814","12,962","30,042","128,051","10,837","111,680",NaN,"5,534",NaN,NaN